services:
  ganache:
    image: trufflesuite/ganache
    ports:
      - "8545:8545"

  org_a:
    build: ./organizations
    environment:
      - ORG_NAME=Org_A
    depends_on:
      - ganache

  org_b:
    build: ./organizations
    environment:
      - ORG_NAME=Org_B
    depends_on:
      - ganache

  org_c:
    build: ./organizations
    environment:
      - ORG_NAME=Org_C
    depends_on:
      - ganache

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - ganache